/**
 * imdbTop250.js
 * 
 * This file contains a manually curated array of movie titles from IMDb's Top 250 list.
 * The OMDb API, which we are using for fetching movie details, restricts searches to specific movie titles
 * or IMDb ID parameters. While OMDb has access to a wide range of movie data, it does not offer a direct
 * endpoint to fetch a list of movies based on rankings or categories, such as IMDb's Top 250.
 * 
 * To create a movie decision maker tool using the OMDb API, we require a pre-existing list of movie titles
 * to randomly select from. As IMDb's own API access comes with a substantial cost (approximately $150,000/year),
 * we opt for this manual approach as a cost-effective alternative. The list provided in this file allows our
 * application to randomly pick a title and then use the OMDb API to fetch and display the details for the
 * selected movie.
 * 
 * The titles included in this array are sourced from IMDb's publicly available Top 250 list, accessible at:
 * https://www.imdb.com/chart/top/
 * The array is static (updated February 2nd, 2024) and may not reflect the current rankings or new entries in the actual IMDb Top 250 list.
 */

const top250MovieTitles = [
    `The Shawshank Redemption`,
    `The Godfather`,
    `The Dark Knight`, 
    `The Godfather Part II`,
    `12 Angry Men`,
    `Schindler's List`, 
    `The Lord of the Rings: The Return of the King`,
    `Pulp Fiction`,
    `The Lord of the Rings: The Fellowship of the Ring`,
    `The Good, the Bad and the Ugly`,
    `Forrest Gump`,
    `Fight Club`,
    `The Lord of the Rings: The Two Towers`,
    `Inception`,
    `Star Wars: Episode V - The Empire Strikes Back`,
    `The Matrix`,
    `Goodfellas`,
    `One Flew Over the Cuckoo's Nest`,
    `Se7en`,
    `It's a Wonderful Life`,
    `Interstellar`,
    `Seven Samurai`,
    `The Silence of the Lambs`,
    `Saving Private Ryan`,
    `City of God`,
    `Life Is Beautiful`,
    `The Green Mile`,
    `Terminator 2: Judgment Day`,
    `Star Wars: Episode IV - A New Hope`,
    `Spider-Man: Across the Spider-Verse`,
    `Back to the Future`,
    `Spirited Away`,
    `The Pianist`,
    `Parasite`,
    `Psycho`,
    `Gladiator`,
    `The Lion King`,
    `Léon: The Professional`,
    `The Departed`,
    `American History X`,
    `Whiplash`,
    `The Prestige`,
    `Grave of the Fireflies`,
    `Harakiri`,
    `The Usual Suspects`,
    `Casablanca`,
    `The Intouchables`,
    `Modern Times`,
    `Cinema Paradiso`,
    `12th Fail`,
    `Rear Window`,
    `Once Upon a Time in the West`,
    `Alien`,
    `City Lights`,
    `Apocalypse Now`,
    `Django Unchained`,
    `Memento`,
    `WALL·E`,
    `Raiders of the Lost Ark`,
    `The Lives of Others`,
    `Sunset Blvd.`,
    `Paths of Glory`,
    `Avengers: Infinity War`,
    `Spider-Man: Into the Spider-Verse`,
    `The Shining`,
    `Witness for the Prosecution`,
    `The Great Dictator`,
    `Aliens`,
    `Inglourious Basterds`,
    `The Dark Knight Rises`,
    `American Beauty`,
    `Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb`,
    `Oldboy`,
    `Coco`,
    `Amadeus`,
    `Toy Story`,
    `The Boat`,
    `Braveheart`,
    `Avengers: Endgame`,
    `Oppenheimer`,
    `Joker`,
    `Princess Mononoke`,
    `Good Will Hunting`,
    `Your Name.`,
    `Once Upon a Time in America`,
    `High and Low`,
    `3 Idiots`,
    `Singin' in the Rain`,
    `Capernaum`,
    `Requiem for a Dream`,
    `Come and See`,
    `Toy Story 3`,
    `Star Wars: Episode VI - Return of the Jedi`,
    `Eternal Sunshine of the Spotless Mind`,
    `The Hunt`,
    `2001: A Space Odyssey`,
    `Reservoir Dogs`,
    `Ikiru`,
    `Lawrence of Arabia`,
    `Poor Things`,
    `The Apartment`,
    `Citizen Kane`,
    `North by Northwest`,
    `M`,
    `Vertigo`,
    `Double Indemnity`,
    `Scarface`,
    `Amélie`,
    `Incendies`,
    `Full Metal Jacket`,
    `A Clockwork Orange`,
    `Heat`,
    `Up`,
    `To Kill a Mockingbird`,
    `The Sting`,
    `A Separation`,
    `Indiana Jones and the Last Crusade`,
    `Hamilton`,
    `Die Hard`,
    `Metropolis`,
    `Like Stars on Earth`,
    `Snatch`,
    `Bicycle Thieves`,
    `L.A. Confidential`,
    `1917`,
    `Taxi Driver`,
    `Downfall`,
    `Dangal`,
    `For a Few Dollars More`,
    `Batman Begins`,
    `Some Like It Hot`,
    `The Wolf of Wall Street`,
    `The Kid`,
    `Green Book`,
    `The Father`,
    `Top Gun: Maverick`,
    `All About Eve`,
    `Judgment at Nuremberg`,
    `The Truman Show`,
    `There Will Be Blood`,
    `Shutter Island`,
    `Casino`,
    `Ran`,
    `Jurassic Park`,
    `The Sixth Sense`,
    `Pan's Labyrinth`,
    `Unforgiven`,
    `A Beautiful Mind`,
    `No Country for Old Men`,
    `The Treasure of the Sierra Madre`,
    `Yojimbo`,
    `The Thing`,
    `Kill Bill: Vol. 1`,
    `Monty Python and the Holy Grail`,
    `The Great Escape`,
    `Finding Nemo`,
    `Rashomon`,
    `The Elephant Man`,
    `Howl's Moving Castle`,
    `Chinatown`,
    `Prisoners`,
    `Dial M for Murder`,
    `Gone with the Wind`,
    `V for Vendetta`,
    `Lock, Stock, and Two Smoking Barrels`,
    `The Secret in Their Eyes`,
    `Raging Bull`,
    `Inside Out`,
    `Three Billboards Outside Ebbing, Missouri`,
    `Trainspotting`,
    `The Bridge on the River Kwai`,
    `Spider-Man: No Way Home`,
    `Godzilla Minus One`,
    `Fargo`,
    `Warrior`,
    `Klaus`,
    `Catch Me If You Can`,
    `Gran Torino`,
    `My Neighbor Totoro`,
    `Million Dollar Baby`,
    `Harry Potter and the Deathly Hallows: Part 2`,
    `Children of Heaven`,
    `Blade Runner`,
    `12 Years a Slave`,
    `Before Sunrise`,
    `The Grand Budapest Hotel`,
    `Ben-Hur`,
    `Barry Lyndon`,
    `Gone Girl`,
    `The Gold Rush`,
    `Hacksaw Ridge`,
    `In the Name of the Father`,
    `Memories of Murder`,
    `On the Waterfront`,
    `The General`,
    `The Deer Hunter`,
    `Dead Poets Society`,
    `Wild Tales`,
    `Mad Max: Fury Road`,
    `Wild Strawberries`,
    `Sherlock Jr.`,
    `The Third Man`,
    `The Wages of Fear`,
    `Monsters, Inc.`,
    `Jaws`,
    `How to Train Your Dragon`,
    `Mr. Smith Goes to Washington`,
    `Mary and Max`,
    `Ford v Ferrari`,
    `Ratatouille`,
    `The Seventh Seal`,
    `Room`,
    `The Big Lebowski`,
    `Tokyo Story`,
    `Rocky`,
    `Hotel Rwanda`,
    `Logan`,
    `Spotlight`,
    `Platoon`,
    `The Terminator`,
    `The Passion of Joan of Arc`,
    `Jai Bhim`,
    `Before Sunset`,
    `The Best Years of Our Lives`,
    `La haine`,
    `Rush`,
    `The Exorcist`,
    `Network`,
    `Stand by Me`,
    `Pirates of the Caribbean: The Curse of the Black Pearl`,
    `The Wizard of Oz`,
    `The Incredibles`,
    `Into the Wild`,
    `Hachi: A Dog's Tale`,
    `The Handmaiden`,
    `To Be or Not to Be`,
    `My Father and My Son`,
    `The Grapes of Wrath`,
    `The Battle of Algiers`,
    `Groundhog Day`,
    `The Sound of Music`,
    `Amores Perros`,
    `Rebecca`,
    `Cool Hand Luke`,
    `The Iron Giant`,
    `The Help`,
    `It Happened One Night`,
    `The 400 Blows`,
    `Drishyam`,
    `Aladdin`
    ];




    